# Generated by Django 4.1.3 on 2022-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivrosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, default='0', max_digits=9)),
            ],
        ),
    ]
